sim:
  n_agents: 50000
  n_steps: 20
  steps: null
  n_claims: 1
  seed: 42
  device: auto
  snapshot_interval: 30
  adoption_threshold: 0.8
  deterministic: true
  seed_fraction: 0.001
  use_tf32: false
town:
  n_neighborhoods: 12
  neighborhood_size_mean: 200.0
  neighborhood_size_std: 50.0
  neighborhood_specs: null
  neighborhood_grid:
  - 3
  - 4
  household_size_mean: 3.0
  household_size_std: 1.0
  workplace_size_mean: 18.0
  school_size_mean: 22.0
  church_size_mean: 40.0
  church_attendance_rate: 0.25
  min_age: 0
  max_age: 90
  children_fraction: 0.22
  senior_fraction: 0.16
  city: null
  data_source: null
  education_levels:
  - none
  - high_school
  - some_college
  - bachelors
  - graduate
  occupation_types:
  - unemployed
  - service
  - blue_collar
  - white_collar
  - professional
  - retired
traits:
  skepticism_mean: 0.5
  skepticism_std: 0.15
  trust_mean: 0.5
  trust_std: 0.15
  personality:
    alpha: 2.0
    beta: 2.0
  cognitive:
    alpha: 2.0
    beta: 2.0
  social:
    alpha: 2.0
    beta: 2.0
  emotion:
    alpha: 2.0
    beta: 2.0
network:
  network_type: small_world
  mean_degree: 8.0
  clustering: 0.3
  rewiring_prob: 0.1
  homophily_strength: 0.75
  geography_strength: 0.5
  geo_scale: 1.5
  intra_neighborhood_p: 0.08
  inter_neighborhood_p: 0.02
  layer_multipliers:
    family: 1.8
    work: 1.2
    school: 1.0
    church: 1.4
    neighborhood: 1.0
world:
  media_channels:
  - mainstream
  moderation_strictness: 0.3
  algorithmic_amplification: 0.7
  outrage_amplification: 0.6
  operator_enabled: false
  emotions_enabled: true
  debunk_intensity: 0.28
  feed_injection_rate: 0.25
  intervention_day: null
  intervention_type: null
  intervention_strength: 0.0
  trust_baselines:
    gov: 0.55
    church: 0.45
    local_news: 0.5
    national_news: 0.45
    friends: 0.6
    outgroups: 0.3
  trust_variance: 0.12
  platform_friction: 0.15
  governance_response_speed: 0.6
  governance_transparency: 0.5
  media_fragmentation: 0.6
  reactance_enabled: false
  trust_update_enabled: false
  trust_erosion_rate: 0.02
  church_centrality: 0.4
  local_media_reach: 0.4
  national_media_reach: 0.35
  gov_reach: 0.3
  truth_campaign_intensity: 0.3
belief_update:
  learning_rate: 0.15
  decay_rate: 0.008
  social_proof_weight: 0.22
  skepticism_dampening: 0.4
  mutual_exclusion_hard: false
  truth_protection_threshold: null
  baseline_belief: 0.05
  social_proof_threshold: 0.55
  eta: 0.25
  rho: 0.25
  alpha: 0.9
  beta: 0.6
  gamma: 0.4
  delta: 0.5
  lambda_skepticism: 0.7
  mu_debunk: 0.8
  exposure_memory_decay: 0.75
  belief_decay: 0.015
  reactance_strength: 0.3
  confirmation_strength: 0.25
  identity_threat_sensitivity: 0.2
sharing:
  base_share_rate: 0.016
  belief_sensitivity: 2.2
  emotion_sensitivity: 0.7
  status_sensitivity: 0.6
  conformity_sensitivity: 0.5
  moderation_risk_sensitivity: 0.4
dual_process:
  s1_emotional_weight: 0.4
  s1_familiarity_weight: 0.3
  s1_narrative_weight: 0.3
  s1_novelty_penalty: 0.2
  s1_fluency_boost: 0.15
  s2_evidence_weight: 0.35
  s2_source_weight: 0.3
  s2_consistency_weight: 0.25
  s2_complexity_penalty: 0.1
  base_s1_tendency: 0.6
  cognitive_load_s1_boost: 0.3
  stakes_s2_boost: 0.25
  need_for_cognition_s2_boost: 0.2
  deliberation_threshold: 0.4
  override_threshold: 0.7
  conflict_detection_threshold: 0.3
  familiarity_decay: 0.95
  fluency_learning_rate: 0.1
sedpnr:
  alpha: 0.1
  gamma: 0.1
  beta_pos_e: 0.5
  beta_neg_e: 0.4
  beta_pos_d: 0.5
  beta_neg_d: 0.6
  lambda_p: 0.01
  lambda_n: 0.01
  mu_e: 0.05
  mu_d: 0.05
moderation:
  warning_effect: 0.35
  downrank_effect: 0.4
strains:
- name: silver_river
  topic: health_rumor
  memeticity: 0.5
  emotional_profile:
    fear: 0.6
    anger: 0.2
    hope: 0.2
  falsifiability: 0.7
  stealth: 0.4
  mutation_rate: 0.05
  violation_risk: 0.3
  is_true: false
  virality: 0.6
  persistence: 0.25
- name: market_shiver
  topic: economic_panic
  memeticity: 0.55
  emotional_profile:
    fear: 0.5
    anger: 0.3
    hope: 0.2
  falsifiability: 0.6
  stealth: 0.45
  mutation_rate: 0.04
  violation_risk: 0.35
  is_true: false
  virality: 0.6
  persistence: 0.25
- name: temple_echo
  topic: moral_spiral
  memeticity: 0.45
  emotional_profile:
    fear: 0.3
    anger: 0.4
    hope: 0.3
  falsifiability: 0.5
  stealth: 0.55
  mutation_rate: 0.06
  violation_risk: 0.4
  is_true: false
  virality: 0.6
  persistence: 0.25
- name: signal_fog
  topic: tech_conspiracy
  memeticity: 0.52
  emotional_profile:
    fear: 0.2
    anger: 0.5
    hope: 0.3
  falsifiability: 0.65
  stealth: 0.5
  mutation_rate: 0.05
  violation_risk: 0.45
  is_true: false
  virality: 0.6
  persistence: 0.25
- name: border_whisper
  topic: outsider_threat
  memeticity: 0.6
  emotional_profile:
    fear: 0.4
    anger: 0.4
    hope: 0.2
  falsifiability: 0.55
  stealth: 0.5
  mutation_rate: 0.04
  violation_risk: 0.5
  is_true: false
  virality: 0.6
  persistence: 0.25
metrics:
  community_backend: auto
  community_max_nodes: 20000
  include_neighborhood_clusters: true
  cluster_penetration_enabled: true
  use_gpu_metrics: true
output:
  save_plots: true
  save_snapshots: true
